apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-umwk
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-gpvq-tenant/rhtap-demo-app/hacbs-test-project-umwk@sha256:0f6ce12140b01ea8e964cdf6525d2a994066c93b042216d339c5111481cd693d
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
